[package]
name = 'full_adder'
version = '0.1.0'
description = 'A full adder'
author = 'Naren Dasan'
license = 'NCSA'

[repository]
url = 'https://github.com/veritas-verilog/full_adder'
version_control = 'git'

[dependencies]
